#[derive(Copy, Clone)]
#[repr(C)]
pub struct sfxinfo_struct {
    pub tagname: *mut ::core::ffi::c_char,
    pub name: [::core::ffi::c_char; 9],
    pub priority: ::core::ffi::c_int,
    pub link: *mut sfxinfo_t,
    pub pitch: ::core::ffi::c_int,
    pub volume: ::core::ffi::c_int,
    pub usefulness: ::core::ffi::c_int,
    pub lumpnum: ::core::ffi::c_int,
    pub numchannels: ::core::ffi::c_int,
    pub driver_data: *mut ::core::ffi::c_void,
}
pub type sfxinfo_t = sfxinfo_struct;
#[derive(Copy, Clone)]
#[repr(C)]
pub struct musicinfo_t {
    pub name: *mut ::core::ffi::c_char,
    pub lumpnum: ::core::ffi::c_int,
    pub data: *mut ::core::ffi::c_void,
    pub handle: *mut ::core::ffi::c_void,
}
pub const sfx_pistol: C2Rust_Unnamed = 1;
pub type C2Rust_Unnamed = ::core::ffi::c_uint;
pub const NUMSFX: C2Rust_Unnamed = 109;
pub const sfx_radio: C2Rust_Unnamed = 108;
pub const sfx_skeatk: C2Rust_Unnamed = 107;
pub const sfx_skesit: C2Rust_Unnamed = 106;
pub const sfx_skeact: C2Rust_Unnamed = 105;
pub const sfx_keendt: C2Rust_Unnamed = 104;
pub const sfx_keenpn: C2Rust_Unnamed = 103;
pub const sfx_ssdth: C2Rust_Unnamed = 102;
pub const sfx_sssit: C2Rust_Unnamed = 101;
pub const sfx_mandth: C2Rust_Unnamed = 100;
pub const sfx_manatk: C2Rust_Unnamed = 99;
pub const sfx_bosdth: C2Rust_Unnamed = 98;
pub const sfx_bospn: C2Rust_Unnamed = 97;
pub const sfx_bossit: C2Rust_Unnamed = 96;
pub const sfx_boscub: C2Rust_Unnamed = 95;
pub const sfx_bospit: C2Rust_Unnamed = 94;
pub const sfx_getpow: C2Rust_Unnamed = 93;
pub const sfx_flamst: C2Rust_Unnamed = 92;
pub const sfx_flame: C2Rust_Unnamed = 91;
pub const sfx_itmbk: C2Rust_Unnamed = 90;
pub const sfx_bdcls: C2Rust_Unnamed = 89;
pub const sfx_bdopn: C2Rust_Unnamed = 88;
pub const sfx_tink: C2Rust_Unnamed = 87;
pub const sfx_chgun: C2Rust_Unnamed = 86;
pub const sfx_metal: C2Rust_Unnamed = 85;
pub const sfx_hoof: C2Rust_Unnamed = 84;
pub const sfx_punch: C2Rust_Unnamed = 83;
pub const sfx_barexp: C2Rust_Unnamed = 82;
pub const sfx_noway: C2Rust_Unnamed = 81;
pub const sfx_vilact: C2Rust_Unnamed = 80;
pub const sfx_bspwlk: C2Rust_Unnamed = 79;
pub const sfx_bspact: C2Rust_Unnamed = 78;
pub const sfx_dmact: C2Rust_Unnamed = 77;
pub const sfx_bgact: C2Rust_Unnamed = 76;
pub const sfx_posact: C2Rust_Unnamed = 75;
pub const sfx_skedth: C2Rust_Unnamed = 74;
pub const sfx_pedth: C2Rust_Unnamed = 73;
pub const sfx_kntdth: C2Rust_Unnamed = 72;
pub const sfx_vildth: C2Rust_Unnamed = 71;
pub const sfx_bspdth: C2Rust_Unnamed = 70;
pub const sfx_spidth: C2Rust_Unnamed = 69;
pub const sfx_cybdth: C2Rust_Unnamed = 68;
pub const sfx_brsdth: C2Rust_Unnamed = 67;
pub const sfx_skldth: C2Rust_Unnamed = 66;
pub const sfx_cacdth: C2Rust_Unnamed = 65;
pub const sfx_sgtdth: C2Rust_Unnamed = 64;
pub const sfx_bgdth2: C2Rust_Unnamed = 63;
pub const sfx_bgdth1: C2Rust_Unnamed = 62;
pub const sfx_podth3: C2Rust_Unnamed = 61;
pub const sfx_podth2: C2Rust_Unnamed = 60;
pub const sfx_podth1: C2Rust_Unnamed = 59;
pub const sfx_pdiehi: C2Rust_Unnamed = 58;
pub const sfx_pldeth: C2Rust_Unnamed = 57;
pub const sfx_skeswg: C2Rust_Unnamed = 56;
pub const sfx_claw: C2Rust_Unnamed = 55;
pub const sfx_vilatk: C2Rust_Unnamed = 54;
pub const sfx_skepch: C2Rust_Unnamed = 53;
pub const sfx_sgtatk: C2Rust_Unnamed = 52;
pub const sfx_sklatk: C2Rust_Unnamed = 51;
pub const sfx_pesit: C2Rust_Unnamed = 50;
pub const sfx_mansit: C2Rust_Unnamed = 49;
pub const sfx_vilsit: C2Rust_Unnamed = 48;
pub const sfx_kntsit: C2Rust_Unnamed = 47;
pub const sfx_bspsit: C2Rust_Unnamed = 46;
pub const sfx_spisit: C2Rust_Unnamed = 45;
pub const sfx_cybsit: C2Rust_Unnamed = 44;
pub const sfx_brssit: C2Rust_Unnamed = 43;
pub const sfx_cacsit: C2Rust_Unnamed = 42;
pub const sfx_sgtsit: C2Rust_Unnamed = 41;
pub const sfx_bgsit2: C2Rust_Unnamed = 40;
pub const sfx_bgsit1: C2Rust_Unnamed = 39;
pub const sfx_posit3: C2Rust_Unnamed = 38;
pub const sfx_posit2: C2Rust_Unnamed = 37;
pub const sfx_posit1: C2Rust_Unnamed = 36;
pub const sfx_telept: C2Rust_Unnamed = 35;
pub const sfx_oof: C2Rust_Unnamed = 34;
pub const sfx_wpnup: C2Rust_Unnamed = 33;
pub const sfx_itemup: C2Rust_Unnamed = 32;
pub const sfx_slop: C2Rust_Unnamed = 31;
pub const sfx_pepain: C2Rust_Unnamed = 30;
pub const sfx_mnpain: C2Rust_Unnamed = 29;
pub const sfx_vipain: C2Rust_Unnamed = 28;
pub const sfx_popain: C2Rust_Unnamed = 27;
pub const sfx_dmpain: C2Rust_Unnamed = 26;
pub const sfx_plpain: C2Rust_Unnamed = 25;
pub const sfx_swtchx: C2Rust_Unnamed = 24;
pub const sfx_swtchn: C2Rust_Unnamed = 23;
pub const sfx_stnmov: C2Rust_Unnamed = 22;
pub const sfx_dorcls: C2Rust_Unnamed = 21;
pub const sfx_doropn: C2Rust_Unnamed = 20;
pub const sfx_pstop: C2Rust_Unnamed = 19;
pub const sfx_pstart: C2Rust_Unnamed = 18;
pub const sfx_firxpl: C2Rust_Unnamed = 17;
pub const sfx_firsht: C2Rust_Unnamed = 16;
pub const sfx_rxplod: C2Rust_Unnamed = 15;
pub const sfx_rlaunc: C2Rust_Unnamed = 14;
pub const sfx_sawhit: C2Rust_Unnamed = 13;
pub const sfx_sawful: C2Rust_Unnamed = 12;
pub const sfx_sawidl: C2Rust_Unnamed = 11;
pub const sfx_sawup: C2Rust_Unnamed = 10;
pub const sfx_bfg: C2Rust_Unnamed = 9;
pub const sfx_plasma: C2Rust_Unnamed = 8;
pub const sfx_dbload: C2Rust_Unnamed = 7;
pub const sfx_dbcls: C2Rust_Unnamed = 6;
pub const sfx_dbopn: C2Rust_Unnamed = 5;
pub const sfx_dshtgn: C2Rust_Unnamed = 4;
pub const sfx_sgcock: C2Rust_Unnamed = 3;
pub const sfx_shotgn: C2Rust_Unnamed = 2;
pub const sfx_None: C2Rust_Unnamed = 0;
pub const NULL: *mut ::core::ffi::c_void = ::core::ptr::null_mut::<::core::ffi::c_void>();
#[no_mangle]
pub static mut S_music: [musicinfo_t; 68] = [
    musicinfo_t {
        name: ::core::ptr::null_mut::<::core::ffi::c_char>(),
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e1m1\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e1m2\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e1m3\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e1m4\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e1m5\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e1m6\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e1m7\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e1m8\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e1m9\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e2m1\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e2m2\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e2m3\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e2m4\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e2m5\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e2m6\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e2m7\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e2m8\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e2m9\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e3m1\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e3m2\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e3m3\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e3m4\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e3m5\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e3m6\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e3m7\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e3m8\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"e3m9\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"inter\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"intro\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"bunny\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"victor\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"introa\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"runnin\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"stalks\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"countd\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"betwee\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"doom\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"the_da\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"shawn\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"ddtblu\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"in_cit\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"dead\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"stlks2\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"theda2\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"doom2\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"ddtbl2\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"runni2\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"dead2\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"stlks3\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"romero\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"shawn2\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"messag\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"count2\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"ddtbl3\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"ampie\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"theda3\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"adrian\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"messg2\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"romer2\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"tense\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"shawn3\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"openin\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"evil\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"ultima\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"read_m\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"dm2ttl\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
    musicinfo_t {
        name: b"dm2int\0".as_ptr() as *const ::core::ffi::c_char as *mut ::core::ffi::c_char,
        lumpnum: 0 as ::core::ffi::c_int,
        data: NULL,
        handle: NULL,
    },
];
#[no_mangle]
pub static mut S_sfx: [sfxinfo_t; 109] = [sfxinfo_t {
    tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
    name: [0; 9],
    priority: 0,
    link: ::core::ptr::null_mut::<sfxinfo_t>(),
    pitch: 0,
    volume: 0,
    usefulness: 0,
    lumpnum: 0,
    numchannels: 0,
    driver_data: ::core::ptr::null_mut::<::core::ffi::c_void>(),
}; 109];
unsafe extern "C" fn c2rust_run_static_initializers() {
    S_sfx = [
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"none\0\0\0\0\0"),
            priority: 0 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"pistol\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"shotgn\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"sgcock\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"dshtgn\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"dbopn\0\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"dbcls\0\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"dbload\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"plasma\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bfg\0\0\0\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"sawup\0\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"sawidl\0\0\0"),
            priority: 118 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"sawful\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"sawhit\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"rlaunc\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"rxplod\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"firsht\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"firxpl\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"pstart\0\0\0"),
            priority: 100 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"pstop\0\0\0\0"),
            priority: 100 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"doropn\0\0\0"),
            priority: 100 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"dorcls\0\0\0"),
            priority: 100 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"stnmov\0\0\0"),
            priority: 119 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"swtchn\0\0\0"),
            priority: 78 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"swtchx\0\0\0"),
            priority: 78 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"plpain\0\0\0"),
            priority: 96 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"dmpain\0\0\0"),
            priority: 96 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"popain\0\0\0"),
            priority: 96 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"vipain\0\0\0"),
            priority: 96 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"mnpain\0\0\0"),
            priority: 96 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"pepain\0\0\0"),
            priority: 96 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"slop\0\0\0\0\0"),
            priority: 78 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"itemup\0\0\0"),
            priority: 78 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"wpnup\0\0\0\0"),
            priority: 78 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"oof\0\0\0\0\0\0"),
            priority: 96 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"telept\0\0\0"),
            priority: 32 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"posit1\0\0\0"),
            priority: 98 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"posit2\0\0\0"),
            priority: 98 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"posit3\0\0\0"),
            priority: 98 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bgsit1\0\0\0"),
            priority: 98 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bgsit2\0\0\0"),
            priority: 98 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"sgtsit\0\0\0"),
            priority: 98 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"cacsit\0\0\0"),
            priority: 98 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"brssit\0\0\0"),
            priority: 94 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"cybsit\0\0\0"),
            priority: 92 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"spisit\0\0\0"),
            priority: 90 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bspsit\0\0\0"),
            priority: 90 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"kntsit\0\0\0"),
            priority: 90 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"vilsit\0\0\0"),
            priority: 90 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"mansit\0\0\0"),
            priority: 90 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"pesit\0\0\0\0"),
            priority: 90 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"sklatk\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"sgtatk\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"skepch\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"vilatk\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"claw\0\0\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"skeswg\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"pldeth\0\0\0"),
            priority: 32 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"pdiehi\0\0\0"),
            priority: 32 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"podth1\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"podth2\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"podth3\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bgdth1\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bgdth2\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"sgtdth\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"cacdth\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"skldth\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"brsdth\0\0\0"),
            priority: 32 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"cybdth\0\0\0"),
            priority: 32 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"spidth\0\0\0"),
            priority: 32 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bspdth\0\0\0"),
            priority: 32 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"vildth\0\0\0"),
            priority: 32 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"kntdth\0\0\0"),
            priority: 32 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"pedth\0\0\0\0"),
            priority: 32 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"skedth\0\0\0"),
            priority: 32 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"posact\0\0\0"),
            priority: 120 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bgact\0\0\0\0"),
            priority: 120 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"dmact\0\0\0\0"),
            priority: 120 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bspact\0\0\0"),
            priority: 100 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bspwlk\0\0\0"),
            priority: 100 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"vilact\0\0\0"),
            priority: 100 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"noway\0\0\0\0"),
            priority: 78 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"barexp\0\0\0"),
            priority: 60 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"punch\0\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"hoof\0\0\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"metal\0\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"chgun\0\0\0\0"),
            priority: 64 as ::core::ffi::c_int,
            link: (&raw mut S_sfx as *mut sfxinfo_t)
                .offset(sfx_pistol as ::core::ffi::c_int as isize)
                as *mut sfxinfo_t,
            pitch: 150 as ::core::ffi::c_int,
            volume: 0 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"tink\0\0\0\0\0"),
            priority: 60 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bdopn\0\0\0\0"),
            priority: 100 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bdcls\0\0\0\0"),
            priority: 100 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"itmbk\0\0\0\0"),
            priority: 100 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"flame\0\0\0\0"),
            priority: 32 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"flamst\0\0\0"),
            priority: 32 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"getpow\0\0\0"),
            priority: 60 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bospit\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"boscub\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bossit\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bospn\0\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"bosdth\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"manatk\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"mandth\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"sssit\0\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"ssdth\0\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"keenpn\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"keendt\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"skeact\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"skesit\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"skeatk\0\0\0"),
            priority: 70 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
        sfxinfo_struct {
            tagname: ::core::ptr::null_mut::<::core::ffi::c_char>(),
            name: ::core::mem::transmute::<[u8; 9], [::core::ffi::c_char; 9]>(*b"radio\0\0\0\0"),
            priority: 60 as ::core::ffi::c_int,
            link: ::core::ptr::null_mut::<sfxinfo_t>(),
            pitch: -1 as ::core::ffi::c_int,
            volume: -1 as ::core::ffi::c_int,
            usefulness: 0 as ::core::ffi::c_int,
            lumpnum: 0 as ::core::ffi::c_int,
            numchannels: -1 as ::core::ffi::c_int,
            driver_data: NULL,
        },
    ];
}
#[used]
#[cfg_attr(target_os = "linux", link_section = ".init_array")]
#[cfg_attr(target_os = "windows", link_section = ".CRT$XIB")]
#[cfg_attr(target_os = "macos", link_section = "__DATA,__mod_init_func")]
static INIT_ARRAY: [unsafe extern "C" fn(); 1] = [c2rust_run_static_initializers];
